"""Add last_seen field in User

Revision ID: 788fc4f20cfa
Revises: 93c207cc831a
Create Date: 2018-02-25 00:47:53.078949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788fc4f20cfa'
down_revision = '93c207cc831a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
